ALTER SESSION SET CONTAINER = ORCLPDB;

CREATE USER USER_APP IDENTIFIED BY "Password123$";

GRANT CONNECT, RESOURCE, DBA TO USER_APP;
GRANT UNLIMITED TABLESPACE TO USER_APP;

ALTER SESSION SET CURRENT_SCHEMA = USER_APP;

CREATE TABLE T_TRANSACTIONS (
    ID VARCHAR2(50) NOT NULL,
    ACCOUNT_ID VARCHAR2(20) NOT NULL,
    TYPE VARCHAR2(10) NOT NULL,
    AMOUNT NUMBER NOT NULL,
    CURRENCY VARCHAR2(5) NOT NULL,
    DESCRIPTION VARCHAR2(100) NOT NULL,
    STATUS VARCHAR2(30),
    PROVIDER_TRANSACTION_ID VARCHAR2(50),
    BALANCE_AFTER NUMBER,
    CREATED_AT TIMESTAMP WITH TIME ZONE,
    CONSTRAINT T_TRANSACTIONS_PK PRIMARY KEY (ID)
);

CREATE OR REPLACE PACKAGE PKG_TRANSACTION AS
    TYPE CursorType IS REF CURSOR;
    PROCEDURE ADD_TRANSACTION(pId IN VARCHAR2, pAccountId IN VARCHAR2, pType IN VARCHAR2, pAmount IN NUMBER, pCurrency IN VARCHAR2,
    pDescription IN VARCHAR2, pStatus IN VARCHAR2, pProviderTransactionId IN VARCHAR2, pBalanceAfter IN NUMBER, pCreatedAt IN VARCHAR, oResult OUT VARCHAR2);
    PROCEDURE GET_TRANSACTION(pAccountId IN VARCHAR2, pStatus IN VARCHAR2, pType IN VARCHAR2, pPage IN NUMBER, pLimit IN NUMBER, rc OUT SYS_REFCURSOR);
    PROCEDURE GET_TRANSACTION_COUNT(pAccountId IN VARCHAR2, pStatus IN VARCHAR2, pType IN VARCHAR2, oCount OUT NUMBER);
END PKG_TRANSACTION;
/
CREATE OR REPLACE PACKAGE BODY PKG_TRANSACTION AS
    PROCEDURE ADD_TRANSACTION(pId IN VARCHAR2, pAccountId IN VARCHAR2, pType IN VARCHAR2, pAmount IN NUMBER, pCurrency IN VARCHAR2, pDescription IN VARCHAR2, pStatus IN VARCHAR2, pProviderTransactionId IN VARCHAR2, pBalanceAfter IN NUMBER, pCreatedAt IN VARCHAR, oResult OUT VARCHAR2) IS
    BEGIN
        INSERT INTO T_TRANSACTIONS (ID, ACCOUNT_ID, TYPE, AMOUNT, CURRENCY, DESCRIPTION, STATUS, PROVIDER_TRANSACTION_ID, BALANCE_AFTER, CREATED_AT)
        VALUES (pId, pAccountId, pType, pAmount, pCurrency, pDescription, pStatus, pProviderTransactionId, pBalanceAfter, TO_TIMESTAMP_TZ(pCreatedAt, 'YYYY-MM-DD"T"HH24:MI:SS"Z"'));
        oResult:='true';
    END ADD_TRANSACTION;

    PROCEDURE GET_TRANSACTION(pAccountId IN VARCHAR2, pStatus IN VARCHAR2, pType IN VARCHAR2, pPage IN NUMBER, pLimit IN NUMBER, rc OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN rc FOR
            SELECT ID, ACCOUNT_ID, TYPE, AMOUNT, CURRENCY, DESCRIPTION, STATUS, PROVIDER_TRANSACTION_ID, BALANCE_AFTER, TO_CHAR(CREATED_AT, 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
            FROM T_TRANSACTIONS
            WHERE (pAccountId = 'null' OR ACCOUNT_ID = pAccountId)
              AND (pStatus = 'null' OR STATUS = pStatus)
              AND (pType = 'null' OR TYPE = pType)
            ORDER BY CREATED_AT DESC
            OFFSET ((pPage - 1) * pLimit) ROWS
            FETCH NEXT pLimit ROWS ONLY;
    END GET_TRANSACTION;

    PROCEDURE GET_TRANSACTION_COUNT(pAccountId IN VARCHAR2, pStatus IN VARCHAR2, pType IN VARCHAR2, oCount OUT NUMBER) IS
    BEGIN
        SELECT COUNT(*) INTO oCount
        FROM T_TRANSACTIONS
        WHERE (pAccountId = 'null' OR ACCOUNT_ID = pAccountId)
          AND (pStatus = 'null' OR STATUS = pStatus)
          AND (pType = 'null' OR TYPE = pType);
        END GET_TRANSACTION_COUNT;
    END PKG_TRANSACTION;
/